In [1]:
import numpy as np

In [216]:
def predict(arg_X, arg_W, arg_b):
    Ŷ = arg_X.dot(arg_W) + arg_b
    return Ŷ

In [118]:
def error(arg_Y, arg_Ŷ):
    Error = arg_Ŷ - arg_Y
    return Error

In [119]:
def mse_loss(arg_Y, arg_Ŷ):
    Loss = error(arg_Y, arg_Ŷ) **2
    return Loss

In [120]:
def mse_cost(arg_Y, arg_Ŷ):
    m = len(arg_Y)
    cost = sum(mse_loss(arg_Y, arg_Ŷ))
    cost /= m
    return (cost)

In [246]:
def fit(arg_X, arg_Y, no_of_iterations, arg_initial_b, arg_initial_w, arg_learning_rate):
    no_of_features = arg_X.shape[1]
    b = 0
    W = np.full(no_of_features, arg_initial_w, dtype=np.float64)
    
    for iteration in range(no_of_iterations):
        Ŷ = predict(arg_X, W, b)
        b -= compute_gradient_bias(arg_X, arg_Y, Ŷ) * arg_learning_rate
        W -= compute_gradient_weights(arg_X, arg_Y, Ŷ) * arg_learning_rate
        print(f"{b}, {W}, {mse_cost(arg_Y, Ŷ):0.4f}")
        
    return (b, W)

In [252]:
def compute_gradient_bias(arg_X, arg_y_i, arg_ŷ_i):
    m = arg_X.shape[1]
    Error = error(arg_y_i, arg_ŷ_i)
    derivative_bias = sum(Error) * 2 / m
    return derivative_bias

def compute_gradient_weights(arg_X, arg_y_i, arg_ŷ_i):
    m = arg_X.shape[1]
    Error = error(arg_y_i, arg_ŷ_i)
    derivative_weight = Error.dot(arg_X) * 2 / m
    return derivative_weight

In [255]:
X = np.array([[1,2], [1,2]])
Y = np.array([2,2])
# Why the hell does it overshoot like this crazy
fit(X, Y, no_of_iterations = 25, arg_initial_b = 0, arg_initial_w = 0, arg_learning_rate = 1)
print()
fit(X, Y, no_of_iterations = 25, arg_initial_b = 0, arg_initial_w = 0, arg_learning_rate = .325)
print()
fit(X, Y, no_of_iterations = 25, arg_initial_b = 0, arg_initial_w = 0, arg_learning_rate = .1)

4.0, [4. 8.], 4.0000
-40.0, [-40. -80.], 484.0000
444.0, [444. 888.], 58564.0000
-4880.0, [-4880. -9760.], 7086244.0000
53684.0, [ 53684. 107368.], 857435524.0000
-590520.0, [ -590520. -1181040.], 103749698404.0000
6495724.0, [ 6495724. 12991448.], 12553713506884.0000
-71452960.0, [-7.1452960e+07 -1.4290592e+08], 1518999334332964.0000
785982564.0, [7.85982564e+08 1.57196513e+09], 183798919454288640.0000
-8645808200.0, [-8.64580820e+09 -1.72916164e+10], 22239669253968924672.0000
95103890204.0, [9.51038902e+10 1.90207780e+11], 2690999979730240274432.0000
-1046142792240.0, [-1.04614279e+12 -2.09228558e+12], 325610997547359046467584.0000
11507570714644.0, [1.15075707e+13 2.30151414e+13], 39398930703230441200025600.0000
-126583277861080.0, [-1.26583278e+14 -2.53166556e+14], 4767270615090883771750154240.0000
1392416056471884.0, [1.39241606e+15 2.78483211e+15], 576839744425996914941291921408.0000
-1.531657662119072e+16, [-1.53165766e+16 -3.06331532e+16], 69797609075545624948677718048768.0000


(0.33333333333333326, array([0.33333333, 0.66666667]))

In [258]:
X = np.array([[1,2], [2,4], [3,6]])
Y = np.array([2, 8, 18])
b, W = fit(X, Y, no_of_iterations = 25, arg_initial_b = 0, arg_initial_w = 0, arg_learning_rate = .01)

X_test = np.array([[3, 3]])

print(predict(X_test, W, b))

0.28, [0.72 1.44], 130.6667
0.3356, [0.9192 1.8384], 17.2304
0.329772, [0.975624 1.951248], 8.6514
0.30719164, [0.99290088 1.98580176], 7.9528
0.2801056268, [0.99943877 1.99887753], 7.8469
0.251870828316, [1.00302529 2.00605058], 7.7859
0.22340711584492, [1.00579534 2.01159068], 7.7287
0.1949663009927804, [1.00833417 2.01666835], 7.6723
0.1666170596351679, [1.01080227 2.02160455], 7.6163
0.13837786556563417, [1.01324366 2.02648732], 7.5608
0.11025343198795459, [1.01567043 2.03134085], 7.5058
0.08224470132528418, [1.01808592 2.03617184], 7.4512
0.0543515837503993, [1.02049109 2.04098219], 7.3971
0.0265737079012045, [1.02288623 2.04577247], 7.3434
-0.0010893733293293045, [1.02527145 2.0505429 ], 7.2902
-0.028638126385277043, [1.0276468  2.05529359], 7.2374
-0.05607302159039494, [1.03001233 2.06002465], 7.1850
-0.08339452891662097, [1.03236808 2.06473616], 7.1331
-0.11060311682993078, [1.0347141  2.06942819], 7.0816
-0.13769925197977456, [1.03705042 2.07410083], 7.0305
-0.1646833991197425

In [240]:
X = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
Y = np.array([18,42,66,90,104])
X.shape

(5, 2)

In [167]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([1,2,3])
print(A)
print(B)
B.dot(A)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3]


array([22, 28])

In [162]:
((np.array([1,2]) - np.array([0,4]))**2).sum()

5

In [115]:
mse_loss(np.array([1,2,3]), np.array([2,4,3]))

array([1, 4, 0])

In [157]:
x = 4 ; y = 6
(x,y) -= (2,3)

SyntaxError: 'tuple' is an illegal expression for augmented assignment (134339085.py, line 2)

In [156]:
y

3